fonts:
  title:
    font: FREESCPT.TTF
    size: 20
  text:
    font: FREESCPT.TTF
    size: 20
texts:
  title:
    text:   FPV Racer
    width:  5
    height: 8
  prename:
    text:   Hans
    width:  165
    height: 33
  surname:
    text:   Mustermann
    width:  142
    height: 13
defaults:
  extension: bmp
  defaultImage: fpvracersch.bmp
  resourcesPath: resources/
  destinationPath: output/